# # "make clean" removes all generated files

# # More detailed: build using ocamlc/ocamlopt + ocamlfind to locate LLVM

# OBJS = ast.cmx sast.cmx codegen.cmx parser.cmx scanner.cmx semant.cmx microc.cmx pprinting.cmx

# heckell : $(OBJS)
# 	ocamlfind ocamlopt -linkpkg -package llvm -package llvm.analysis $(OBJS) -o heckell

# scanner.ml : scanner.mll
# 	ocamllex scanner.mll

# parser.ml parser.mli : parser.mly
# 	ocamlyacc parser.mly

# %.cmo : %.ml
# 	ocamlc -c $<

# %.cmi : %.mli
# 	ocamlc -c $<

# %.cmx : %.ml
# 	ocamlfind ocamlopt -c -package llvm $<

# ### Generated by "ocamldep *.ml *.mli" after building scanner.ml and parser.ml
# ast.cmo :
# ast.cmx :
# codegen.cmo : ast.cmo
# codegen.cmx : ast.cmx
# heckell.cmo : semant.cmo scanner.cmo parser.cmi codegen.cmo ast.cmo pprinting.cmo
# heckell.cmx : semant.cmx scanner.cmx parser.cmx codegen.cmx ast.cmx pprinting.cmx
# parser.cmo : ast.cmo parser.cmi
# parser.cmx : ast.cmx parser.cmi
# scanner.cmo : parser.cmi
# scanner.cmx : parser.cmx
# semant.cmo : ast.cmo
# semant.cmx : ast.cmx
# parser.cmi : ast.cmo


# .PHONY : clean
# clean :
# 	ocamlbuild -clean
# 	rm -rf scanner.ml parser.ml parser.mli *.cmx *.cmo



########################################################################
########################################################################
# Make sure ocamlbuild can find opam-managed packages: first run
#
# eval `opam config env`
#
# Easiest way to build: using ocamlbuild, which in turn uses ocamlfind
########################################################################

.PHONY : all
all : heckell

# More detailed: build using ocamlc/ocamlopt + ocamlfind to locate LLVM

OBJS = ast.cmx sast.cmx codegen.cmx parser.cmx scanner.cmx semant.cmx pprinting.cmx heckell.cmx

heckell : $(OBJS)
	ocamlfind ocamlopt -linkpkg -package llvm -package llvm.analysis $(OBJS) -o heckell

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

%.cmx : %.ml
	ocamlfind ocamlopt -c -package llvm $<


### Generated by "ocamldep *.ml *.mli" after building scanner.ml and parser.ml
ast.cmo :
ast.cmx :
codegen.cmo : ast.cmo
codegen.cmx : ast.cmx
heckell.cmo : semant.cmo scanner.cmo parser.cmi codegen.cmo ast.cmo
heckell.cmx : semant.cmx scanner.cmx parser.cmx codegen.cmx ast.cmx
parser.cmo : ast.cmo parser.cmi
parser.cmx : ast.cmx parser.cmi
scanner.cmo : parser.cmi
scanner.cmx : parser.cmx
semant.cmo : ast.cmo
semant.cmx : ast.cmx
parser.cmi : ast.cmo



# "make clean" removes all generated files

.PHONY : clean
clean :
	# ocamlbuild -clean
	rm -rf testall.log *.diff heckell scanner.ml parser.ml parser.mli
	rm -rf *.cmx *.cmi *.cmo *.cmx *.o *.s *.ll *.out *.exe



