########################################################################
# Make sure ocamlbuild can find opam-managed packages: first run
#
# eval `opam config env`
#
# Easiest way to build: using ocamlbuild, which in turn uses ocamlfind
########################################################################

.PHONY : all
all : heckell ut-sets.o

# More detailed: build using ocamlc/ocamlopt + ocamlfind to locate LLVM

OBJS = ast.cmx sast.cmx pprinting.cmx parser.cmx scanner.cmx semant.cmx codegen.cmx heckell.cmx

YOPT =

heckell : $(OBJS)
	ocamlfind ocamlopt -linkpkg -package llvm -package llvm.analysis $(OBJS) -o heckell
	# ocamlfind ocamlopt -linkpkg $(OBJS) -o heckell


scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc $(YOPT) parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

%.cmx : %.ml
	# ocamlfind ocamlopt -c $<
	ocamlfind ocamlopt -c -package llvm $<

# Testing the ut-sets

ut-sets : ut-sets.c
	cc -o ut-sets -DBUILD_TEST ut-sets.c

### Generated by "ocamldep *.ml *.mli" after building scanner.ml and parser.ml
ast.cmo :
ast.cmx :
codegen.cmo : sast.cmo ast.cmo
codegen.cmx : sast.cmx ast.cmx
heckell.cmo : semant.cmo scanner.cmo pprinting.cmo parser.cmi
heckell.cmx : semant.cmx scanner.cmx pprinting.cmx parser.cmx
parser.cmo : ast.cmo parser.cmi
parser.cmx : ast.cmx parser.cmi
pprinting.cmo : sast.cmo ast.cmo
pprinting.cmx : sast.cmx ast.cmx
sast.cmo : ast.cmo
sast.cmx : ast.cmx
scanner.cmo : parser.cmi
scanner.cmx : parser.cmx
semant.cmo : sast.cmo pprinting.cmo ast.cmo
semant.cmx : sast.cmx pprinting.cmx ast.cmx
parser.cmi : ast.cmo



# "make clean" removes all generated files

.PHONY : clean
clean :
	# ocamlbuild -clean
	rm -rf testall.log *.diff heckell scanner.ml parser.ml parser.mli
	rm -rf *.cmx *.cmi *.cmo *.cmx *.o *.s *.ll *.out *.exe
	rm -rf ut-sets


